# This is a config for E2B sandbox template.
# You can use template ID (jc8s7cxhs6of2jq97fxn) or template name (loveable-app) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("loveable-app") # Sync sandbox
# sandbox = await AsyncSandbox.create("loveable-app") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('loveable-app')

team_id = "73a1cb04-aabe-47bf-8a8f-43b20d0730fe"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "loveable-app"
template_id = "jc8s7cxhs6of2jq97fxn"
